### PR TITLE
Implement get_profile_picture()

### PR DESCRIPTION
**Pull request by sairam4123**
Implement get_profile_picture() and rename current get_profile_picture as get_profile_picture_raw()

### CODE REVIEW

**Review by Drachenfrucht1 — APPROVED** [review]

**Review by Drachenfrucht1 — APPROVED** [review]

**Comment by Drachenfrucht1** [comment]
Doesn't work currently probably because of https://github.com/discord/gamesdk-and-dispatch/issues/122.

**Comment by sairam4123** [comment]
Alright, thanks!On 14-Jun-2021 5:21 PM, Drachenfrucht1 ***@***.***> wrote:
Doesn't work currently probably because of discord/gamesdk-and-dispatch#122.

**Comment by sairam4123** [comment]
@Drachenfrucht1 Can you give this a test again?

**Comment by Drachenfrucht1** [comment]
Still not working.

**Pull request closed without merging**
