### PR TITLE
Add contribution section to README

### PR DESCRIPTION
**Pull request by Drachenfrucht1**
Outlines the way that one can contribute to the project or get help when needed.
Includes a link to a discord server as suggested in #30.

### CODE REVIEW

**Review by summertimejordi — APPROVED** [review]
Also looks like you added the voice manager, nice

**Review by sairam4123 — APPROVED** [review]
Looks good to me.
Better move voice manager to different PR, so I can test it.

**Comment by Drachenfrucht1** [comment]
I accidentally branched off the wrong branch. Fixed it by rebasing.

**Comment by sairam4123** [comment]
Ok, cool.

**Comment by summertimejordi** [comment]
Can you separate the contribution section commit to merge?

**Pull request merged**
