### PR TITLE
WIP: Applications manager

### PR DESCRIPTION
**Pull request by Drachenfrucht1**
Implements the application manager:
Current problems:
- `get_ticket` doesn't work at all, but I think it is discord's fault (there's an error in the client's dev console).
- another external dependency is needed. I precompiled it for windows and Linux and a second download, but that is not an optimal solution. I will have to check again if Godot provides the functionality that is needed.

### CODE REVIEW

**Comment by summertimejordi** [comment]
What's the external dependency?

**Comment by Drachenfrucht1** [comment]
libsodium - a crypto library

**Comment by sairam4123** [comment]
So what do plan to do? Fixing the current problems?

**Comment by sairam4123** [comment]
What's the use of the get_ticket btw?

**Pull request closed without merging**
