### PR TITLE
Xml docs

### PR DESCRIPTION
**Pull request by Drachenfrucht1**
This pull request adds xml documentation for the project. The xml docs will automatically be included in the engine and can be displayed in the engine (like the normal godot documentation). 

This pull request also includes a github action to automatically parse the xml docs and upload them to github pages. This way documentation has to only be written once.

### CODE REVIEW

**Comment by sairam4123** [comment]
Can you try creating a new branch and cherry picking them? Because this will mess the history.

**Comment by Drachenfrucht1** [comment]
I will squash all commits into one when I'm finished working on the PR.

**Review by sairam4123 — APPROVED** [review]
Looking good!

**Comment by sairam4123** [comment]
MacOS actions are still failing.

**Pull request closed without merging**
